# Temperature sensor settings (i2c)
ADDRESS = 0x5a
REGISTER_AMBIENT_TEMP = 0x06
REGISTER_OBJECT_TEMP = 0x07
REGISTER_OBJECT2_TEMP = 0x08
TIME_BETWEEN_TRIES = 0.1
NUM_VALUES_TO_AVERAGE_OVER = 5
MAX_NUM_TRIES = 10
MAX_ALLOWED_ERROR = 20

# GPIO pin configuration
MOTOR_A_PIN = 16
MOTOR_B_PIN = 18
MOTOR_E_PIN = 22
TOUCH_SENSOR_BOTTOM_PIN = 24
TOUCH_SENSOR_TOP_PIN = 26
TOUCH_SENSOR_BACK_PIN = 28
RELAY_PIN = 15

PLATE_SWITCH_TIMEOUT = 0.5 # How long we should keep the "button pressed" for the place to recognize it